# Feature flag constants definitions
ENABLE_NEO4J = "ENABLE_NEO4J"
ENABLE_VECTOR_SEARCH = "ENABLE_VECTOR_SEARCH"
ENABLE_RAG = "ENABLE_RAG"
ENABLE_LLM = "ENABLE_LLM"
ENABLE_DEAD_CODE_ENGINE = "ENABLE_DEAD_CODE_ENGINE"
